/** Fresh loopback-only HTTP/SQL acceptance; no shared data or external providers. */
import assert from 'node:assert/strict';
import { randomUUID, createHmac } from 'node:crypto';
import jwt from 'jsonwebtoken';
import { once } from 'node:events';
import type { AddressInfo } from 'node:net';
import type { Role } from '@prisma/client';
import app from '../src/app';
import db from '../src/lib/prisma';
import { signAccessToken } from '../src/lib/jwt';
import { CURRENT_TERMS_VERSION, CURRENT_PRIVACY_VERSION } from '../src/domain/onboarding.policy';
import { NUTRITION_GUIDANCE_POLICY_VERSION } from '../src/domain/deterministic-nutrition-report.policy';
import { buildMealLibraryRecipeSignature } from '../src/domain/meal-library-signature.policy';
import { MEAL_LIBRARY_SAFETY_POLICY_VERSION } from '../src/domain/meal-library-safety-evidence.policy';
import { libraryBaseRevisionKey } from '../src/services/meal-base-admission.service';
import { loadMealReviewContext } from '../src/services/meal-case-context.service';
import { CertifiedSlotFallbackService } from '../src/services/certified-slot-fallback.service';
import { UpcomingPlanPreparationService } from '../src/services/upcoming-plan-preparation.service';
import { assertNoAutomaticSlotReplacement } from '../src/services/rejected-slot-recipes.service';

async function main() {
  const target = new URL(process.env.DATABASE_URL ?? '');
  assert.equal(target.hostname, '127.0.0.1'); assert.equal(target.port, '55488'); assert.equal(target.pathname, '/kainara_review_filters');
  assert.equal(process.env.NODE_ENV, 'test'); assert.equal(process.env.CLINICAL_CLARIFICATIONS_ENABLED, 'true');
  assert.equal(process.env.MEMBERSHIP_ENABLED, 'false');
  for (const key of ['GEMINI_API_KEY', 'SMTP_USER', 'BREVO_API_KEY', 'PAYMONGO_SECRET_KEY']) assert(!(process.env[key] ?? '').trim(), `External provider ${key} must be disabled.`);
  assert.equal(await db.user.count(), 0, 'Use a fresh task-owned database.');
  const nativeFetch = globalThis.fetch;
  globalThis.fetch = (input, init) => { assert.equal(new URL(String(input)).hostname, '127.0.0.1', 'No external calls'); return nativeFetch(input, init); };
  const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
  const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}/api`;
  const account = (role: Role) => db.user.create({ data: { role, name: `Synthetic ${role}`, email: `${randomUUID()}@example.invalid`, passwordHash: 'NON_LOGIN_FIXTURE', emailVerified: true, onboardingDone: true, tosAccepted: true, acceptedTermsVersion: CURRENT_TERMS_VERSION, acceptedPrivacyVersion: CURRENT_PRIVACY_VERSION, healthDataConsentedAt: new Date() } });
  type Actor = Awaited<ReturnType<typeof account>>;
  const request = async (actor: Actor, path: string, method = 'GET', body?: unknown) => {
    const response = await fetch(base + path, { method, headers: { Authorization: `Bearer ${signAccessToken({ userId: actor.id, email: actor.email, role: actor.role })}`, 'Content-Type': 'application/json' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    return { status: response.status, body: await response.json() as any };
  };
  const ok = async (promise: ReturnType<typeof request>) => { const result = await promise; assert.equal(result.status, 200, JSON.stringify(result.body)); return result.body.data; };
  const checks: string[] = []; const pass = (name: string) => { checks.push(name); console.log(`PASS ${name}`); };
  try {
    const member = await account('USER'), rnd = await account('NUTRITIONIST'), other = await account('NUTRITIONIST'), admin = await account('ADMIN');
    const reviewer = await db.nutritionistProfile.create({ data: { userId: rnd.id, isVerified: true, prcLicenseNumber: rnd.id, prcLicenseExpiry: new Date('2099-01-01') } });
    const certifier = await db.nutritionistProfile.create({ data: { userId: other.id, isVerified: true, prcLicenseNumber: other.id, prcLicenseExpiry: new Date('2099-01-01') } });
    const now = new Date();
    const profile = await db.userProfile.create({ data: { userId: member.id, revision: 1, safetyRevision: 1, age: 28, biologicalSex: 'MALE', heightCm: 170, weightKg: 65, goal: 'MAINTAIN', activityLevel: 'SEDENTARY', dietaryPreference: 'OMNIVORE', ricePreference: 'WITH_RICE', dailyCalorieTarget: 2000, planningReportVersion: 1 } });
    for (const domain of ['CONDITION', 'ALLERGY'] as const) await db.safetyProfileEntry.create({ data: { userId: member.id, domain, canonicalCode: 'NONE', displayName: 'None', originalText: 'None', normalizedText: 'none', provenance: 'PREDEFINED', supportState: 'SUPPORTED', policyReference: 'STRUCTURED_RESTRICTIONS_V1' } });
    await db.healthCondition.create({ data: { userId: member.id, condition: 'NONE' } }); await db.allergy.create({ data: { userId: member.id, allergen: 'NONE' } });
    await db.nutritionReport.create({ data: { userId: member.id, version: 1, profileRevision: 1, acknowledgedAt: now, foodsToAvoid: [], foodsToLimit: [], foodsRecommended: [], drinksGuidance: [], generalSummary: 'Synthetic guidance', basedOnConditions: [], basedOnAllergies: [] } });
    await db.nutritionReportVersion.create({ data: { userId: member.id, version: 1, profileRevision: 1, acknowledgedAt: now, policyVersion: NUTRITION_GUIDANCE_POLICY_VERSION, content: {}, profileSnapshot: { profile: JSON.parse(JSON.stringify(profile)) } } });
    const rice = await db.foodItem.create({ data: { name: 'Rice, well-milled, boiled', source: 'FNRI', category: 'GRAINS', calories: 130, proteinG: 2, carbsG: 28, fatG: 0.1, sodium: 10, sugar: 0, fiber: 1, potassium: 20, phosphorus: 10, saturatedFat: 0 } });
    const food = await db.foodItem.create({ data: { name: 'Synthetic vegetable', source: 'FNRI', category: 'PRODUCE', calories: 200, proteinG: 10, carbsG: 20, fatG: 5 } });
    const library = async (name: string, sugarG: number | null = 10, verified = true) => {
      const ingredients = [{ ingredientName: food.name, foodItemId: food.id, quantity: 300, unit: 'g', category: 'PRODUCE', dataSource: 'FNRI' as const, position: 0 }];
      const nutrition = { calories: 600, proteinG: 30, carbsG: 60, fatG: 15 };
      const signature = buildMealLibraryRecipeSignature({ mealName: name, mealType: 'LUNCH', ...nutrition, ingredients });
      const meal = await db.mealLibrary.create({ data: { mealName: name, mealType: 'LUNCH', ...nutrition, sugarG, sodiumMg: 100, fiberG: 5, potassiumMg: 200, phosphorusMg: 80, saturatedFatG: 2, description: 'Synthetic measured fixture', status: 'APPROVED', dietaryTags: ['OMNIVORE'], recipeSignature: signature, verifiedByNutritionistId: certifier.id, safetyReviewedByNutritionistId: certifier.id, safetyReviewedAt: now, safetyEvidenceStatus: 'COMPLETE', safetyEvidenceOrigin: 'NUTRITIONIST_REVIEW', safetyPolicyVersion: MEAL_LIBRARY_SAFETY_POLICY_VERSION, safetyEvidenceRevision: 1, certifiedEvidenceRevision: 1, conditionDeclarationState: 'REVIEWED_NONE_DECLARED', allergenDeclarationState: 'REVIEWED_NONE_DECLARED', crossContactAssessment: 'ASSESSED_NO_KNOWN_RISK', nutritionEvidenceSource: 'FNRI_RECONCILED', nutritionServingDescription: '300 g', riceRole: 'PAIR_WITH_RICE', riceRoleReviewStatus: 'REVIEWED', applicableMealTypes: { create: { mealType: 'LUNCH' } }, ingredients: { create: ingredients } } });
      if (verified) await db.mealBaseVerification.create({ data: { targetKind: 'LIBRARY_MEAL', targetId: meal.id, revisionKey: libraryBaseRevisionKey(signature, meal.description), status: 'VERIFIED', reviewedByNutritionistId: certifier.id, reviewedAt: now, rationale: 'Synthetic base verification.' } });
      return meal;
    };
    const eligible = await library('ZZZ zero-sugar plate', 0), unknown = await library('Unknown sugar plate', null), unverified = await library('Unverified plate', 0, false);
    for (let i = 0; i < 125; i++) await library(`Catalog plate ${String(i).padStart(3, '0')}`);
    let cycleRevision = 0;
    const slot = async () => {
      const start = new Date(now.getTime() + ++cycleRevision * 86400000);
      const cycle = await db.mealPlanCycle.create({ data: { id: randomUUID(), userId: member.id, cycleRevision, planType: 'WEEKLY', startDate: start, endDate: new Date(start.getTime() + 86400000), preparationOpensAt: now, shoppingDeadlineAt: now, expectedSlotCount: 1, snapshot: { create: { userId: member.id, profileRevision: 1, safetyRevision: 1, nutritionReportVersion: 1, weightKg: 65, activityLevel: 'SEDENTARY', goal: 'MAINTAIN', dailyCalorieTarget: 2000, dailyMacroTargets: {}, dietaryPreference: 'OMNIVORE', ricePreference: 'WITH_RICE', planningGeographyLevel: 'NATIONAL' } } } });
      return db.mealPlan.create({ data: { userId: member.id, planGroupId: cycle.id, mealType: 'LUNCH', mealName: 'Synthetic original', calories: 800, proteinG: 40, carbsG: 80, fatG: 20, scheduledDate: start, status: 'PENDING_REVIEW', claimedByNutritionistId: reviewer.id, claimedAt: new Date() } });
    };
    const currentKey = async (id: string) => (await loadMealReviewContext(id))!.contextKey;
    const options = async (id: string, filters = {}, cursor?: string, actor = rnd, key?: string) => request(actor, `/nutritionist/queue/${id}/swap-options?` + new URLSearchParams({ expectedContextKey: key ?? await currentKey(id), filters: JSON.stringify(filters), ...(cursor ? { cursor } : {}) }));
    const initial = await slot(), key = await currentKey(initial.id);
    const preview = await ok(options(initial.id, { sugarG: { max: 0 } }));
    assert.equal(preview.options.length, 1); assert.equal(preview.options[0].id, eligible.id); assert.equal(preview.summary.matchedCount, 1); assert.equal(preview.summary.unknownExcludedCount, 1);
    const selected = preview.options[0]; assert(selected.pairedRiceG > 0); assert.equal(selected.nutrients.sodiumMg, 100 + selected.pairedRiceG / 10); assert(selected.calories > 600); assert(selected.ingredients.some((item: any) => item.name === rice.name));
    assert.equal((await options(initial.id, {}, undefined, member)).status, 403); assert.equal((await options(initial.id, {}, undefined, other)).status, 409);
    pass('Full-catalog search finds a zero-valued candidate beyond row 120, excludes unknown and unverified values, includes rice and enforces role/claim');
    const pages = new Set<string>(); let cursor: string | undefined; let total = 0;
    do { const page = await ok(options(initial.id, {}, cursor)); total = page.summary.matchedCount; for (const item of page.options) { assert(!pages.has(item.id)); pages.add(item.id); } cursor = page.nextCursor ?? undefined; } while (cursor);
    assert.equal(total, 127); assert.equal(pages.size, total); assert(!pages.has(unverified.id)); assert(pages.has(unknown.id));
    pass('Authoritative post-policy counts and all pages include every eligible result without duplicate rows');
    for (const filters of [{ sodiumMg: { max: -1 } }, { sugarG: { min: 2, max: 1 } }, { sodiumG: { max: 1 } }]) assert.equal((await options(initial.id, filters)).status, 400);
    assert.equal((await options(initial.id, { sodiumMg: { max: selected.nutrients.sodiumMg - 0.0001 } })).body.data.summary.matchedCount, 0);
    assert.equal((await ok(options(initial.id, { sodiumMg: { max: selected.nutrients.sodiumMg } }))).summary.matchedCount, 127);
    await db.foodItem.update({ where: { id: rice.id }, data: { sodium: null } });
    const noSide = await ok(options(initial.id, { sodiumMg: { max: 1000 } })); assert.equal(noSide.summary.matchedCount, 0); assert.equal(noSide.summary.unknownExcludedCount, 127);
    await db.foodItem.update({ where: { id: rice.id }, data: { sodium: 10 } });
    pass('Fixed-unit numeric boundaries and missing required side values fail closed');
    const payload = { libraryMealId: selected.id, expectedContextKey: key, expectedVersion: preview.expectedVersion, expectedRecipeSignature: selected.recipeSignature, expectedEvidenceRevision: selected.evidenceRevision, expectedServingKey: selected.servingKey, filters: preview.filters, note: 'Reviewed the exact complete synthetic plate.' };
    const swap = (body: unknown, id = initial.id) => request(rnd, `/nutritionist/queue/${id}/swap`, 'POST', body);
    assert.equal((await swap({ ...payload, filters: { sodiumMg: { max: 0 } } })).status, 409);
    await db.mealLibrary.update({ where: { id: eligible.id }, data: { sugarG: 1 } }); assert.equal((await swap(payload)).status, 409);
    await db.mealLibrary.update({ where: { id: eligible.id }, data: { sugarG: 0 } });
    await db.foodItem.update({ where: { id: rice.id }, data: { compositionRevision: { increment: 1 } } }); assert.equal((await swap(payload)).status, 409);
    await db.foodItem.update({ where: { id: rice.id }, data: { compositionRevision: 0 } });
    const withheld = await db.mealReviewLineage.create({ data: { key: `recipe:${eligible.id}`, state: 'QUARANTINED' } });
    assert.equal((await swap(payload)).status, 409);
    await db.mealReviewLineage.update({ where: { id: withheld.id }, data: { state: 'PUBLISHED' } });
    await db.nutritionistProfile.update({ where: { id: certifier.id }, data: { prcLicenseExpiry: new Date(0) } });
    assert.equal((await swap(payload)).status, 409);
    await db.nutritionistProfile.update({ where: { id: certifier.id }, data: { prcLicenseExpiry: new Date('2099-01-01') } });
    pass('Quarantine and expired recipe-verifier credentials cannot be bypassed by a previously filtered choice');
    pass('Final swap rechecks filters, extended base values and side composition even when the recipe signature stays unchanged');
    await db.nutritionistProfile.update({ where: { id: reviewer.id }, data: { prcLicenseExpiry: new Date(0) } }); assert.equal((await swap(payload)).status, 403);
    await db.nutritionistProfile.update({ where: { id: reviewer.id }, data: { prcLicenseExpiry: new Date('2099-01-01') } });
    const concurrent = await Promise.all([swap(payload), swap(payload)]); assert.equal(concurrent.filter(result => result.status === 200).length, 1);
    const replacement = await db.mealPlan.findUniqueOrThrow({ where: { id: concurrent.find(result => result.status === 200)!.body.data.replacementPlanId }, include: { servingComponents: true } });
    assert.equal(replacement.status, 'PENDING_REVIEW'); assert.equal(replacement.reviewApprovalCount, 0); assert.equal(replacement.calories, selected.calories); assert.equal(replacement.nutritionistId, null); assert.equal(replacement.servingComponents.find(item => item.componentType === 'COOKED_RICE')!.quantityG, selected.pairedRiceG); assert.equal(await db.mealPlanReviewDecision.count(), 0);
    pass('Expired credentials fail; concurrent swaps publish one exact composed serving which still needs separate approval');
    const held = await slot(), heldKey = await currentKey(held.id), search = await ok(options(held.id, { sugarG: { max: 0 } }));
    const outcome = { kind: 'NO_SUITABLE_REPLACEMENT', searchReceipt: search.searchReceipt };
    assert.equal((await request(rnd, `/nutritionist/review/${held.id}`, 'PATCH', { action: 'reject', expectedContextKey: heldKey, note: 'short', replacementOutcome: outcome })).status, 400);
    assert.equal((await request(rnd, `/nutritionist/review/${held.id}`, 'PATCH', { action: 'reject', expectedContextKey: heldKey, note: 'No suitable plate after clinical inspection.', replacementOutcome: { ...outcome, searchReceipt: preview.searchReceipt } })).status, 409);
    const receiptSecret = createHmac('sha256', process.env.JWT_SECRET!).update('rnd-replacement-search').digest('hex');
    const expired = jwt.sign(search.summary, receiptSecret, { algorithm: 'HS256', audience: 'rnd-replacement-search', expiresIn: -1 });
    assert.equal((await request(rnd, `/nutritionist/review/${held.id}`, 'PATCH', { action: 'reject', expectedContextKey: heldKey, note: 'An expired search must be refreshed.', replacementOutcome: { ...outcome, searchReceipt: expired } })).status, 409);
    assert.equal((await request(other, `/nutritionist/review/${held.id}`, 'PATCH', { action: 'reject', expectedContextKey: heldKey, note: 'Another reviewer cannot reuse this receipt.', replacementOutcome: outcome })).status, 409);
    assert.equal((await request(rnd, `/nutritionist/review/${held.id}`, 'PATCH', { action: 'reject', expectedContextKey: heldKey, note: 'Tampered counts cannot be submitted.', replacementOutcome: { ...outcome, searchReceipt: search.searchReceipt + 'x' } })).status, 409);
    const count = await db.mealPlan.count(); const result = await ok(request(rnd, `/nutritionist/review/${held.id}`, 'PATCH', { action: 'reject', expectedContextKey: heldKey, note: 'Even the numeric match is unsuitable after clinical inspection.', replacementOutcome: outcome }));
    assert.equal(result.replacementPlanId, null); assert.equal(await db.mealPlan.count(), count);
    const saved = await db.mealPlan.findUniqueOrThrow({ where: { id: held.id } }); assert.equal(saved.status, 'REJECTED'); assert.equal(saved.supersededByMealPlanId, null); assert.equal(saved.fallbackAvailable, false);
    assert.equal((await CertifiedSlotFallbackService.replaceWithBestCertified({ mealPlanId: held.id, tolerance: .15, reasonCode: 'SHOPPING_DEADLINE_WIDER_TOLERANCE', expectedStatus: 'REJECTED' })).replaced, false);
    assert.equal(await db.mealPlan.count(), count); const decision = await db.mealPlanReviewDecision.findFirstOrThrow({ where: { mealPlanId: held.id } });
    assert.equal((decision.evidenceSnapshot as any).replacementOutcome.search.matchedCount, 1); assert.equal((decision.evidenceSnapshot as any).contextKey, heldKey);
    pass('A context-bound signed search and comprehensive rationale record no suitable replacement, retain the rejected slot and stop fallback/provider calls');
    await assert.rejects(assertNoAutomaticSlotReplacement(db, held), { errorCode: 'RND_REPLACEMENT_HELD' });
    const competing = await db.mealPlan.create({ data: { userId: held.userId, planGroupId: held.planGroupId,
      mealType: held.mealType, scheduledDate: held.scheduledDate, mealName: 'Synthetic competing row', calories: 800,
      proteinG: 40, carbsG: 80, fatG: 20, status: 'PENDING_REVIEW', claimedByNutritionistId: reviewer.id, claimedAt: new Date() } });
    assert.equal((await CertifiedSlotFallbackService.replaceWithBestCertified({ mealPlanId: competing.id, tolerance: .15, reasonCode: 'SHOPPING_DEADLINE_WIDER_TOLERANCE', expectedStatus: 'PENDING_REVIEW' })).replaced, false);
    await UpcomingPlanPreparationService.reconcileDeadline(member.id, held.planGroupId);
    assert.equal((await db.mealPlan.findUniqueOrThrow({ where: { id: competing.id } })).status, 'PENDING_REVIEW');
    const beforeCompeting = await db.mealPlan.count();
    await ok(request(rnd, `/nutritionist/review/${competing.id}`, 'PATCH', { action: 'reject', expectedContextKey: await currentKey(competing.id), note: 'Independent rejection also respects the recorded slot hold.' }));
    assert.equal(await db.mealPlan.count(), beforeCompeting);
    pass('Slot holds also block deadline, certified, raw and AI replacement paths for competing rows');
    const empty = await slot(), emptyKey = await currentKey(empty.id), emptySearch = await ok(options(empty.id, { sodiumMg: { max: 0 } }));
    assert.equal(emptySearch.summary.matchedCount, 0);
    await ok(request(rnd, `/nutritionist/review/${empty.id}`, 'PATCH', { action: 'reject', expectedContextKey: emptyKey,
      note: 'No eligible plate meets the explicit sodium limit.', replacementOutcome: { kind: 'NO_SUITABLE_REPLACEMENT', searchReceipt: emptySearch.searchReceipt } }));
    assert.equal((await db.mealPlanReviewDecision.findFirstOrThrow({ where: { mealPlanId: empty.id } })).decision, 'REJECT');
    pass('An exhausted search records zero matches separately from clinical rejection of remaining numeric matches');
    const audit = await db.auditEvent.findFirstOrThrow({ where: { entityId: held.id, action: 'MEAL_PLAN_REJECTED' } });
    const inspected = await ok(request(admin, `/admin/audit-history/${audit.id}/review-context`)); assert.equal(inspected.decisions[0].evidenceSnapshot.replacementOutcome.search.filters.sugarG.max, 0);
    assert.equal((await request(member, `/admin/audit-history/${audit.id}/review-context`)).status, 403); assert.equal(await db.auditEvent.count({ where: { actorUserId: admin.id, action: 'ADMIN_REVIEW_SENSITIVE_DETAILS_ACCESSED' } }), 1);
    pass('Case-scoped admin oversight shows saved filters, counts, rationale and reviewed context and records sensitive access');
    const stale = await slot(), staleKey = await currentKey(stale.id), staleSearch = await ok(options(stale.id)); await db.mealPlan.update({ where: { id: stale.id }, data: { calories: 801 } });
    assert.equal((await request(rnd, `/nutritionist/review/${stale.id}`, 'PATCH', { action: 'reject', expectedContextKey: staleKey, note: 'Outdated search must never be accepted.', replacementOutcome: { kind: 'NO_SUITABLE_REPLACEMENT', searchReceipt: staleSearch.searchReceipt } })).status, 409);
    assert.equal(await db.mealPlanReviewDecision.count({ where: { mealPlanId: stale.id } }), 0);
    pass('Outdated meal context cannot commit a search outcome or resurrect a stale decision');
    console.log(JSON.stringify({ target: 'task-owned loopback PostgreSQL', checks, accounts: await db.user.count(), libraryMeals: await db.mealLibrary.count() }));
  } finally { await new Promise<void>(resolve => server.close(() => resolve())); await db.$disconnect(); globalThis.fetch = nativeFetch; }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
