import type { AdminAnalytics } from './useAdminAnalytics';
/** Synthetic fixtures for administrator statistics tests. */
export const analyticsFixture: AdminAnalytics = {
  generatedAt: '2026-10-04T05:00:00.000Z',
  totalUsers: 20,
  totalNutritionists: 4,
  verifiedNutritionists: 2,
  activeMealPlans: 3,
  approvedUpcomingMealSlots: 10,
  pendingReviews: 5,
  libraryCount: 60,
  totalMealLogs: 8,
  totalFoodItems: 1500,
  usdaFoodItems: 200,
  totalAliases: 900,
  overdueReviews: 2,
  activeReviewClaims: 1,
  expiredVerifiedNutritionists: 1,
  completeLibraryEvidence: 30,
  incompleteLibraryEvidence: 20,
  staleLibraryEvidence: 10,
  failedGenerationJobs24h: 1,
  stuckGenerationJobs: 1,
  aiSuccess24h: 4,
  aiFailures24h: 2,
  adaptationReviews30d: 3,
  pendingPlansStartingSoon: 4,
  activeConditionClearances: 5,
  rawRecipeCandidates: 100,
  planningAiOperations30d: 6,
  activeClearancesByCondition: [],
  aiUsageByOperation30d: [],
  planSelectionsByProvenance30d: [],
};
